### ISSUE TITLE
Feature request: update only

### ISSUE THREAD

**Issue by irsdl** [dnet/burp-oauth#3]
I need to use this extension only to update the requests that already have OAuth header. That would be great if we could have an option in a config file to enable or disable this.

**Comment by dnet** [comment]
Sounds nice, would you like to provide the patch?

**Comment by dnet** [comment]
Longer version: it looks like the Signpost library reuses the header if one is already defined, so I'm not sure you'd like this functionality, as it'd mean reusing nonces, (most probably) resulting in rejected requests. So it's not as simple as adding an `if (OAuthConfig.updateOnly) { ... }`, thus I'm not really motivated right now to solve this, but if anyone offers a patch, I'd be happy to review and quite possibly merge it.

**Comment by irsdl** [comment]
At the moment, when it sees the authorization header, it just ignores it. It should update it instead.

**Comment by dnet** [comment]
It doesn't ignore it, it signs with the same parameters (including nonce), resulting in the same signature. Since this is similar to #1, this discussion should be continued there; see my comment there with the three item list.
