### ISSUE TITLE
Authorization header is missing

### ISSUE THREAD

**Issue by irsdl** [dnet/burp-oauth#5]
When using this extension and send a request to scanner, the OAuth header is missing from some of the requests but it is in some... it is very strange behaviour. you can monitor it via Logger++ or by using another burp suite in front of it.
Also, it did not add itself to the following request:
###### 

POST /oauth1/somethinghere HTTP/1.1
User-Agent: Java/1.8.0_66
Host: 192.168.200.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 9

name=test
###### 

However, by converting the above POST request to GET, it was adding the appropriate header.

**Comment by irsdl** [comment]
It seems it particularly has problems with "Content-Type: application/x-www-form-urlencoded"

**Comment by dnet** [comment]
Thanks, I could reproduce the issue.
